export const GetProgramName = (subdomain: string) => {
  const courseMap: { [key: string]: string } = {
    ABCOM: "Bachelor of Arts in Communication",
    ABMMA: "Bachelor of Arts in Multimedia Arts",
    AHM: "Associate in Hotel Management",
    BACOMM: "Bachelor of Arts in Communication",
    BARNCII: "Bartending NC II",
    BEED: "Bachelor of Elementary Education",
    BMMA: "Bachelor of Multimedia Arts",
    "BPP NCII": "Bread and Pastry Production NC II",
    BSA: "Bachelor of Science in Accountancy",
    BSAIS: "Bachelor of Science in Accounting Information System",
    BSAT: "Bachelor of Science in Accounting Technology",
    BSB: "Bachelor of Science in Biology",
    BSBA: "Bachelor of Science in Business Administration",
    BSC: "Bachelor of Science in Criminology",
    BSCS: "Bachelor of Science in Computer Science",
    BSE: "Bachelor of Science in Entrepreneurship",
    BSED: "Bachelor of Secondary Education",
    BSHM: "Bachelor of Science in Hospitality Management",
    BSHRM: "Bachelor of Science in Hotel and Restaurant Management",
    BSIT: "Bachelor of Science in Information Technology",
    BSMLS: "Bachelor of Science in Medical Laboratory Science",
    BSMT: "Bachelor of Science in Marine Transportation",
    BSN: "Bachelor of Science in Nursing",
    BSNED: "Bachelor of Science in Nursing Education",
    BSOT: "Bachelor of Science in Occupational Therapy",
    BSP: "Bachelor of Science in Psychology",
    BSPSY: "Bachelor of Science in Psychology",
    BSPT: "Bachelor of Science in Physical Therapy",
    BSRT: "Bachelor of Science in Radiologic Technology",
    BSTM: "Bachelor of Science in Tourism Management",
    BSTRM: "Bachelor of Science in Travel Management",
    CCNCII: "Contact Center Services NC II",
    "CCPIII-TAFE": "Certificate in Culinary Arts (TAFE)",
    CGNCII: "Caregiving NC II",
    "CGNCII (T)": "Caregiving NC II (Test)",
    CHSNCII: "Computer Hardware Servicing NC II",
    CTP: "Certificate in Teaching Program",
    DB: "Diploma in Business",
    "DBM-KENT": "Diploma in Business Management (Kent)",
    DM: "Diploma in Marketing",
    "DMM-KENT": "Diploma in Marketing Management (Kent)",
    EIMNCII: "Electrical Installation and Maintenance NC II",
    FBSNCII: "Food and Beverage Services NC II",
    FL: "Foreign Language",
    HSKNCII: "Housekeeping NC II",
    MAP: "Master of Arts in Psychology",
    "MAP (YIBU)": "Master of Arts in Psychology (YIBU)",
    MBA: "Master of Business Administration",
    "MBA (YIBU)": "Master of Business Administration (YIBU)",
    MD: "Doctor of Medicine",
    "MD(TEST)": "Doctor of Medicine (Test)",
    MISICT: "Master in Information Systems and Information Technology",
    MSN: "Master of Science in Nursing",
    PNCIV: "Practical Nursing NC IV",
    "PRE-DENT": "Pre-Dentistry",
    SMAWNCI: "Shielded Metal Arc Welding NC I",
    SMAWNCII: "Shielded Metal Arc Welding NC II",
    VACOMLIT: "Visual Arts and Communication Literacy",
    WSA: "Welding Skills Assessment",
    SCMCS: "School of Communication, Multimedia, and Computer Studies",
    SNAHS: "School of Nursing and Allied Health Sciences",
    SMLS: "School of Medical Laboratory Science",
    SITHM: "School of International Tourism and Hospitality Management",
    SASE: "School of Arts and Sciences Education",
  }

  return courseMap[subdomain.toUpperCase()] || "Unknown Course"
}

export const GetProgramDescription = (subdomain: string) => {
  const courseMap: { [key: string]: string } = {
    ABCOM: "Bachelor of Arts in Communication",
    ABMMA: "Bachelor of Arts in Multimedia Arts",
    AHM: "Associate in Hotel Management",
    BACOMM: "Bachelor of Arts in Communication",
    BARNCII: "Bartending NC II",
    BEED: "Bachelor of Elementary Education",
    BMMA: "Bachelor of Multimedia Arts",
    "BPP NCII": "Bread and Pastry Production NC II",
    BSA: "Bachelor of Science in Accountancy",
    BSAIS: "Bachelor of Science in Accounting Information System",
    BSAT: "Bachelor of Science in Accounting Technology",
    BSB: "Bachelor of Science in Biology",
    BSBA: "Bachelor of Science in Business Administration",
    BSC: "Bachelor of Science in Criminology",
    BSCS: "Bachelor of Science in Computer Science",
    BSE: "Bachelor of Science in Entrepreneurship",
    BSED: "Bachelor of Secondary Education",
    BSHM: "Bachelor of Science in Hospitality Management",
    BSHRM: "Bachelor of Science in Hotel and Restaurant Management",
    BSIT: "Bachelor of Science in Information Technology",
    BSMLS: "Bachelor of Science in Medical Laboratory Science",
    BSMT: "Bachelor of Science in Marine Transportation",
    BSN: "Bachelor of Science in Nursing",
    BSNED: "Bachelor of Science in Nursing Education",
    BSOT: "Bachelor of Science in Occupational Therapy",
    BSP: "Bachelor of Science in Psychology",
    BSPSY: "Bachelor of Science in Psychology",
    BSPT: "Bachelor of Science in Physical Therapy",
    BSRT: "Bachelor of Science in Radiologic Technology",
    BSTM: "Bachelor of Science in Tourism Management",
    BSTRM: "Bachelor of Science in Travel Management",
    CCNCII: "Contact Center Services NC II",
    "CCPIII-TAFE": "Certificate in Culinary Arts (TAFE)",
    CGNCII: "Caregiving NC II",
    "CGNCII (T)": "Caregiving NC II (Test)",
    CHSNCII: "Computer Hardware Servicing NC II",
    CTP: "Certificate in Teaching Program",
    DB: "Diploma in Business",
    "DBM-KENT": "Diploma in Business Management (Kent)",
    DM: "Diploma in Marketing",
    "DMM-KENT": "Diploma in Marketing Management (Kent)",
    EIMNCII: "Electrical Installation and Maintenance NC II",
    FBSNCII: "Food and Beverage Services NC II",
    FL: "Foreign Language",
    HSKNCII: "Housekeeping NC II",
    MAP: "Master of Arts in Psychology",
    "MAP (YIBU)": "Master of Arts in Psychology (YIBU)",
    MBA: "Master of Business Administration",
    "MBA (YIBU)": "Master of Business Administration (YIBU)",
    MD: "Doctor of Medicine",
    "MD(TEST)": "Doctor of Medicine (Test)",
    MISICT: "Master in Information Systems and Information Technology",
    MSN: "Master of Science in Nursing",

    PNCIV: "Practical Nursing NC IV",
    "PRE-DENT": "Pre-Dentistry",
    SMAWNCI: "Shielded Metal Arc Welding NC I",
    SMAWNCII: "Shielded Metal Arc Welding NC II",
    VACOMLIT: "Visual Arts and Communication Literacy",
    WSA: "Welding Skills Assessment",
    SCMCS: "School of Communication, Multimedia, and Computer Studies",
    SNAHS: "School of Nursing and Allied Health Sciences",
    SMLS: "School of Medical Laboratory Science",
    SITHM: "School of International Tourism and Hospitality Management",
    SASE: "School of Arts and Sciences Education",
  }

  return courseMap[subdomain.toUpperCase()] || "Unknown Course"
}
